app = 'flessner-umami-db'
primary_region = 'fra'

[build]
image = 'postgres:17.2'

[env]
PGDATA = '/data/pgdata'
# POSTGRES_PASSWORD

[[mounts]]
source = 'data'
destination = '/data'

[[services]]
protocol = 'tcp'
internal_port = 5432
auto_start_machines = false
min_machines_running = 1

[[services.ports]]
port = 5432
handlers = ['pg_tls']
