app = 'flessner-bitwarden'
primary_region = 'fra'

[build]

[[mounts]]
source = 'data'
destination = '/var/lib/tailscale'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1

[[vm]]
size = 'shared-cpu-1x'
