app = 'flessner-umami-db'
primary_region = 'ams'

[build]
image = 'postgres:18-alpine'

[env]
# POSTGRES_PASSWORD

[[mounts]]
source = 'pg_data'
destination = '/var/lib/postgresql'
initial_size = '10gb'

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 256
