app = 'flessner-umami'
primary_region = 'fra'

[build]
image = 'ghcr.io/umami-software/umami:postgresql-latest'

[env]
DATABASE_TYPE = 'postgresql'
# APP_SECRET
# DATABASE_URL

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
