app = 'flessner-umami'
primary_region = 'ams'

[build]
image = 'ghcr.io/umami-software/umami:postgresql-latest'

[env]
DISABLE_TELEMETRY = '1'
# APP_SECRET
# DATABASE_URL

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = false
min_machines_running = 1

[[http_service.checks]]
interval = '30s'
timeout = '5s'
grace_period = '60s'
method = 'GET'
path = '/api/heartbeat'

[[vm]]
size = 'shared-cpu-1x'
memory = '768mb'
cpus = 1
memory_mb = 768
