app = 'flessner-owui'
primary_region = 'ams'

[build]
image = 'ghcr.io/open-webui/open-webui:latest'

[[mounts]]
source = 'data'
destination = '/app/backend/data'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
max_machines_running = 1
